# Generated by Django 5.1.1 on 2024-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image2',
            field=models.ImageField(default='images/default.jpg', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image3',
            field=models.ImageField(default='images/default.jpg', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image4',
            field=models.ImageField(default='images/default.jpg', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image5',
            field=models.ImageField(default='images/default.jpg', upload_to='collection/'),
            preserve_default=False,
        ),
    ]
