# Generated by Django 5.1.1 on 2024-10-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_image2_collection_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image5',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collection')),
            ],
        ),
    ]
