# Generated by Django 5.1.1 on 2024-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_collection_image_remove_collection_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image2',
            field=models.ImageField(default='', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image3',
            field=models.ImageField(default='', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image4',
            field=models.ImageField(default='', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image5',
            field=models.ImageField(default='', upload_to='collection/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
