# Generated by Django 5.1.1 on 2024-10-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collection_image_collection_image2_collection_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='image',
            new_name='image1',
        ),
    ]
