# Generated by Django 5.1.1 on 2024-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
