# Generated by Django 5.1.1 on 2024-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_full_name_contact_ismingiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='xabar',
        ),
    ]
