# Generated by Django 5.1.1 on 2024-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(default='', upload_to='blog/'),
            preserve_default=False,
        ),
    ]
