# Generated by Django 5.1.1 on 2024-10-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='full_name',
            new_name='ismingiz',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='xabar',
        ),
    ]
