# Generated by Django 5.1.1 on 2024-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_image_about_image1_about_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='telegram',
            field=models.CharField(default='', max_length=202),
            preserve_default=False,
        ),
    ]
